<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function compareIp($clientIp)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT u.id FROM AppBundle:User u WHERE (:clientIp BETWEEN u.startIpAddress AND u.endIpAddress)')
                    ->setParameter('clientIp', $clientIp)
                    ->getResult();
    }
}
