imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    image_cache: "%kernel.root_dir%/../var/images"
    thumbnail_size: "104,"
    collections:
      - { id: "eai1", image: "eai1.jpg" }
      - { id: "eai2", image: "eai2.jpg" }
      - { id: "eol", image: "eol.jpg" }
      - { id: "moc", image: "moc.jpg" }
      - { id: "ecj", image: "ecj.jpg" }
    default_backend_image_format: 'jpg'
    link_to_registration: "http://www.nationallizenzen.de/ind_inform_registration"
    lock_image: "images/locked.png"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        name:        "gdses"
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    cache:
        app: cache.adapter.filesystem

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        metsService: "@mets_service"
        thumbnail_size: "%thumbnail_size%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_solarium:
    endpoints:
        default:
            scheme: http
            host: "%solr_host%"
            port: 8443
            path: /solr
            core: nlh
            timeout: 5
    clients:
        default:
            endpoints: [default]

subugoe_find:
    default_query: "doctype:work"
    default_sort: ""
    feed_sort: "date_modified DESC"
    feed_rows: 15
    feed_category: facet_product
    feed_fields: ["nonsort", "date_indexed", "id"]
    facets:
      - { title: facet_product, field: facet_product }
      - { title: facet_creator, field: facet_creator }
      - { title: facet_place_publish, field: facet_place_publish }
      - { title: facet_publisher, field: facet_publisher }
      - { title: year_publish, field: year_publish }
      - { title: docstrct, field: docstrct }
      - { title: genre, field: genre }
      - { title: facet_subject_topic, field: facet_subject_topic }
      - { title: lang, field: lang }

knp_paginator:
    page_range: 7                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: sliding.html.twig  # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

liip_imagine:
    resolvers:
       default:
          web_path: ~

    driver: imagick
    filter_sets:
        cache: ~
        collections:
            quality: 75
            filters:
                thumbnail: { size : [640, 640], mode : outbound }

services:
    twig.extension.tree:
        class: Fuz\Jordan\Twig\Extension\TreeExtension
        tags:
            - { name: twig.extension }

oneup_flysystem:
    adapters:
        storage:
            local:
                directory: "%kernel.root_dir%/../var/storage"
    filesystems:
        nlh:
            adapter: storage

guzzle:
    clients:
        auth:
            base_url: "https://www.nationallizenzen.de/"
